default_settings:
  html_config:
    displayModeBar: true
    displaylogo: false
    modeBarButtonsToRemove:
    - lasso2d
    - select2d
    responsive: true
energy_safety:
  height: 600
  risk_zones: true
  title: Energy Consumption vs. Safety Incidents
  trendline: ols
process_efficiency:
  annotations:
  - text: Higher efficiency doesn't always mean safer processes
    x: 0.5
    y: -0.15
  efficiency_range:
  - 85
  - 100
  height: 500
  title: Process Efficiency vs. Safety by Type
theme:
  bar:
    marker_line_color: rgb(8, 48, 107)
    marker_line_width: 1
    opacity: 0.8
  colorway:
  - '#1f77b4'
  - '#ff7f0e'
  - '#2ca02c'
  - '#d62728'
  - '#9467bd'
  - '#8c564b'
  - '#e377c2'
  - '#7f7f7f'
  - '#bcbd22'
  - '#17becf'
  font:
    family: Arial, sans-serif
    size: 12
  heatmap:
    colorscale: RdBu_r
    showscale: true
  legend:
    orientation: h
    x: 1
    xanchor: right
    y: 1.02
    yanchor: bottom
  margin:
    b: 60
    l: 60
    r: 60
    t: 60
  paper_bgcolor: white
  plot_bgcolor: rgba(240, 240, 240, 0.5)
  scatter:
    marker:
      line:
        color: DarkSlateGrey
        width: 1
      size: 10
    opacity: 0.7
visualizations:
  catalyst_analysis: true
  energy_safety: true
  kpi_dashboard: true
  parameter_correlation: true
  process_efficiency: true
  process_hierarchy: true
  roi_projection: true
  safety_optimization: true
